name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  test-java-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          # cache: maven
      - name: Run Maven tests
        run: mvn test
